language: shell

os:
    - linux

jobs:
  include:
   - dist: xenial
   - dist: bionic
   - dist: focal
   - dist: trusty
   - dist: precise

script:
    - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
    - sudo cpanm Date::Parse
    - make test
    - if command -v shellcheck > /dev/null 2>&1  ; then ./shell-ci-build.sh ; fi
    - if command -v shellcheck > /dev/null 2>&1  ; then shellcheck ./check_ssl_cert test/unit_tests.sh ; fi
