language: shell

os:
    - linux

$ different distros to test different OpenSSL versions
jobs:
  include:
   - dist: xenial
   - dist: bionic
   - dist: focal
   - dist: trusty
   - dist: precise

script:
    - make test
    - ./shell-ci-build.sh
    - shellcheck ./check_ssl_cert test/unit_tests.sh
