language: shell

os:
    - linux

jobs:
  include:
   - dist: xenial
   - dist: bionic
   - dist: focal
   - dist: trusty
   - dist: precise

script:
    - curl -L https://cpanmin.us | perl - App::cpanminus
    - ~/perl5/bin/cpanm Date::Parse
    - make test
    - ./shell-ci-build.sh
    - shellcheck ./check_ssl_cert test/unit_tests.sh
