name: Test

on:
  push:
    branches:
      - $default-branch
      - development
      - master
  # Run tests for any PRs
  pull_request:
  workflow_dispatch:

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'debian:9'
          - 'debian:10'
          - 'ubuntu:16.04'
          - 'ubuntu:18.04'
          - 'ubuntu:20.04'
          - 'ubuntu:20.10'
          - 'alpine:3.13'
          - 'centos:7'
          - 'centos:8'
          - 'fedora:32'
          - 'fedora:33'
        include:
          - distro: 'debian:testing'
            pre: >-
              apt-get update &&
              apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl
          - distro: 'debian:10'
            pre: >-
              apt-get update &&
              apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl
          - distro: 'debian:9'
            pre: >-
              apt-get update &&
              apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl
          - distro: 'ubuntu:20.10'
            pre: >-
              apt-get update &&
              apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl
          - distro: 'ubuntu:20.04'
            pre: >-
              apt-get update &&
              apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl
          - distro: 'ubuntu:16.04'
            pre: >-
              apt-get update &&
              apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl
          - distro: 'ubuntu:18.04'
            pre: >-
              apt-get update &&
              apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl
          - distro: 'alpine:edge'
            pre: >-
              apk add -U bash &&
              apk add nmap shellcheck curl sudo perl make wget bzip2 file openssl
          - distro: 'alpine:3.13'
            pre: >-
              apk add -U bash &&
              apk add nmap shellcheck curl sudo perl make wget bzip2 file openssl
          - distro: 'fedora:rawhide'
            pre: >-
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file openssl hostname
          - distro: 'fedora:34'
            pre: >-
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file openssl
          - distro: 'fedora:33'
            pre: >-
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file openssl
          - distro: 'fedora:32'
            pre: >-
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file openssl
          - distro: 'centos:7'
            pre: >-
              yum install -y nmap curl sudo perl make bzip2 file openssl perl-ExtUtils-MakeMaker perl-Test-Simple &&
              scversion="stable"; curl -Ls "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv && cp "shellcheck-${scversion}/shellcheck" /usr/bin/
          - distro: 'centos:8'
            pre: >-
              dnf install -y nmap curl sudo perl make bzip2 file openssl &&
              scversion="stable"; curl -Ls "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv && cp "shellcheck-${scversion}/shellcheck" /usr/bin/
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run the tests on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_ssl_cert -v ${PWD}:/check_ssl_cert ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus \
              && cpanm --sudo install Date::Parse \
              && make test \
              && if command -v shellcheck > /dev/null 2>&1  ; then ./shell-ci-build.sh ; fi \
              && if command -v shellcheck > /dev/null 2>&1  ; then shellcheck ./check_ssl_cert test/unit_tests.sh ; fi'
